/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_TEST_PB_H_INCLUDED
#define PB_TEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Test {
    pb_callback_t message;
} Test;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Test_init_default                        {{{NULL}, NULL}}
#define Test_init_zero                           {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Test_message_tag                         1

/* Struct field encoding specification for nanopb */
#define Test_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   message,           1)
#define Test_CALLBACK pb_default_field_callback
#define Test_DEFAULT NULL

extern const pb_msgdesc_t Test_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Test_fields &Test_msg

/* Maximum encoded size of messages (where known) */
/* Test_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
